gitee:
  oauth:
    clientid: "266407dfe065073d7c2b9b75183a9558e
    clientsecret: "578cb20e60e35b5326ace875fd3b8085
    callback: "http://1



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.majiang.com
  mapper-locations: classpath:resourc

#数据库mysql5.7
spring:
  datasource:
    driver-class-name: com.mysql.
    url: jdbc:mysqlseSSL=false&serverTimezone=UTC
    username: 
    password: 
    type: com.alib

#redis的springboot配置
  jpa:
    show-sql: true # 启动日志sql语句
  redis:
    database: 0 # 数据库索引默认0
    host: 
    port: 
    password: 
# springboot 2.0 redis默认客户端已换成lettuce
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8   # 连接池中的最大空闲连接 默认 8
        min-idle: 0   # 连接池中的最小空闲连接 默认 0
    timeout: 5000     # 最大超时时间


#qq邮箱的配置
#邮箱配置
#平台地址，这里用的是qq邮箱，使用其他邮箱请更换
  mail:
    host: smt
    username: 2@qq.com  自己的邮箱
    password: cxba发送短信的授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true  #spri.enable=true
    default-encoding: utf-8 #编码格式


#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
