gitee:
  oauth:
    clientid: "266407dfe065073d7c2b9b75183a9558ee8b6661b6587fc88e20277cbe2b6d3a"
    clientsecret: "578cb20e60e35b5326ace875fd3b80850caf83b00b5ed2f98270a5d44197b887"
    callback: "http://localhost:8888/callback"

spring:
  datasource:
    url: jdbc:h2:~/community
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.majiang.community.mapper
  mapper-locations: classpath:resources/mapper/*.xml