gitee:
  oauth:
    clientid: "266407dfe065073d7c2b9b75183a9558ee8b6661b6587fc88e20277cbe2b6d3a"
    clientsecret: "578cb20e60e35b5326ace875fd3b80850caf83b00b5ed2f98270a5d44197b887"
    callback: "http://121.40.218.249:8888/callback"


#h2数据库的配置
#spring:
#  datasource:
#    url: jdbc:h2:~/community
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      settings:
#        web-allow-others: true
#      path: /h2
#      enabled: true
#    jdbc:h2:tcp://lpf-pqcm:9092/~/community
# http://lpf-pqcm:9092/home/lpf
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/test
#  spring.datasource.username=root
#  spring.datasource.password=
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.majiang.community.mapper
  mapper-locations: classpath:resources/mapper/*.xml

#数据库mysql5.7
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.218.249:3306/lpf_commity?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#redis的springboot配置
  jpa:
    show-sql: true # 启动日志sql语句
  redis:
    database: 0 # 数据库索引默认0
    host: 121.40.218.249  # 连接ip
    port: 6379 # 连接端口
    password: root # 连接密码
# springboot 2.0 redis默认客户端已换成lettuce
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8   # 连接池中的最大空闲连接 默认 8
        min-idle: 0   # 连接池中的最小空闲连接 默认 0
    timeout: 5000     # 最大超时时间


#qq邮箱的配置
#邮箱配置
#平台地址，这里用的是qq邮箱，使用其他邮箱请更换
  mail:
    host: smtp.qq.com
    username: 2677086147@qq.com #2568034812@qq.com  自己的邮箱
    password: #发送短信的授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true  #spring.mail.properties.mail.smtp.ssl.enable=true
    default-encoding: utf-8 #编码格式




